import {and,eq} from "drizzle-orm";
import {database} from "@/db";
import {students} from "@/db/schema";
import {requireTeacher} from "@/lib/auth";
import {PageHead,EmptyState,Value} from "@/components/ui";
import {Field} from "@/components/action-form";
import {ReportForm} from "@/components/report-form";
import {buildReportDraft} from "@/lib/report-service";
import {monthPeriod} from "@/lib/format";
export default async function NewReport({searchParams}:{searchParams:Promise<{student?:string;start?:string;end?:string}>}){const access=await requireTeacher();const params=await searchParams;const rows=await database().select({id:students.id,name:students.name}).from(students).where(and(eq(students.accessCodeId,access.id),eq(students.active,true))).orderBy(students.name).limit(1000);const period=monthPeriod();let draft:Awaited<ReturnType<typeof buildReportDraft>>|undefined;let error="";if(params.student&&params.start&&params.end){try{draft=await buildReportDraft(access.id,{studentId:params.student,periodStart:params.start,periodEnd:params.end});}catch{error="Não foi possível preparar o relatório. Confira o aluno e as datas (até um ano).";}}return <><PageHead title="Relatório mensal" description="Transforme suas anotações em um acompanhamento profissional."/>{rows.length?<><form className="panel mb-6 grid items-end gap-4 md:grid-cols-[1.5fr_1fr_1fr_auto]"><Field name="student" label="Aluno" options={rows.map(s=>({value:s.id,label:s.name}))} value={params.student} required/><Field name="start" label="De" type="date" value={params.start??period.start} required/><Field name="end" label="Até" type="date" value={params.end??period.end} required/><button className="button">Preparar prévia</button></form>{error&&<p role="alert" className="mb-5 text-red-800">{error}</p>}{draft&&<div className="grid items-start gap-6 lg:grid-cols-[1.5fr_1fr]"><section className="panel"><h2 className="mb-5">{draft.student.name} · {draft.student.subject}</h2><ReportForm data={draft}/></section><section className="panel"><h2 className="mb-5">Dados do acompanhamento</h2><Value label="Professor">{draft.teacher.professionalName||draft.teacher.name}</Value><Value label="Presença">{draft.snapshot.attendance}</Value><Value label="Evolução avaliada">{draft.snapshot.progress}</Value><Value label="Objetivos">{draft.snapshot.goals}</Value></section></div>}</>:<EmptyState/>}</>;}
