import type {FieldSpec} from "@/components/action-form";
import {today,lessonStatuses} from "./format";
type Values=Record<string,string|number|boolean|Date|null>;
export function withValues(fields:FieldSpec[],values?:Values):FieldSpec[]{return fields.map(f=>({...f,value:values&&f.name in values?typeof values[f.name]==="boolean"?String(values[f.name]):values[f.name] instanceof Date?undefined:values[f.name] as string|number|null:f.value}));}
export const profileFields:FieldSpec[]=[{name:"name",label:"Nome do professor",required:true},{name:"professionalName",label:"Nome profissional"},{name:"phone",label:"Telefone",type:"tel"},{name:"email",label:"E-mail (opcional)",type:"email"},{name:"mainSubject",label:"Disciplina principal",required:true},{name:"additionalSubjects",label:"Outras disciplinas"},{name:"photoUrl",label:"Foto (opcional)",type:"image"},{name:"logoUrl",label:"Logo (opcional)",type:"image"}];
export function studentFields():FieldSpec[]{return [{name:"name",label:"Nome completo",required:true},{name:"birthDate",label:"Data de nascimento (opcional)",type:"date"},{name:"age",label:"Idade (opcional)",type:"number",min:1,max:120},{name:"grade",label:"Ano / série",required:true},{name:"school",label:"Escola (opcional)"},{name:"subject",label:"Disciplina",required:true},{name:"startDate",label:"Data de início",type:"date",required:true,value:today()},{name:"frequency",label:"Frequência das aulas",placeholder:"2 vezes por semana"},{name:"responsibleName",label:"Nome do responsável"},{name:"responsiblePhone",label:"Telefone do responsável",type:"tel"},{name:"responsibleEmail",label:"E-mail do responsável (opcional)",type:"email"},{name:"mainGoal",label:"Objetivo principal",type:"textarea"},{name:"difficulties",label:"Principais dificuldades",type:"textarea"},{name:"strengths",label:"Pontos fortes",type:"textarea"},{name:"notes",label:"Observações importantes",type:"textarea"}];}
export function packageFields():FieldSpec[]{return [{name:"totalLessons",label:"Aulas contratadas",type:"number",required:true,min:1,max:1000,value:8},{name:"value",label:"Valor do pacote (R$)",type:"number",required:true,min:0,step:"0.01"},{name:"startDate",label:"Início do pacote",type:"date",required:true,value:today()},{name:"renewalDate",label:"Renovação prevista (opcional)",type:"date"}];}
export function lessonFields():FieldSpec[]{return [{name:"date",label:"Data",type:"date",required:true,value:today()},{name:"startTime",label:"Horário",type:"time",required:true,value:"14:00"},{name:"duration",label:"Duração (minutos)",type:"number",min:5,max:480,required:true,value:60},{name:"status",label:"Presença",options:lessonStatuses,value:"completed"},{name:"justifiedAbsence",label:"Falta justificada",type:"checkbox"},{name:"content",label:"Conteúdo trabalhado",type:"textarea",placeholder:"Ex.: Equações de primeiro grau"},{name:"activities",label:"Atividades realizadas",type:"textarea"},{name:"lessonRating",label:"Como foi a aula?",options:["Excelente","Muito boa","Boa","Com dificuldade","Precisou de bastante apoio"],value:"Boa"},{name:"participation",label:"Participação",options:["Alta","Boa","Regular","Baixa"],value:"Boa"},{name:"achievement",label:"Principal avanço",type:"textarea"},{name:"difficulty",label:"Dificuldade observada",type:"textarea"},{name:"homework",label:"Atividade para casa",type:"textarea"},{name:"nextFocus",label:"Foco da próxima aula",type:"textarea"}];}
export const indicators=[{key:"comprehension",label:"Compreensão"},{key:"autonomy",label:"Autonomia"},{key:"participation",label:"Participação"},{key:"organization",label:"Organização"},{key:"concentration",label:"Concentração"},{key:"activityCompletion",label:"Realização das atividades"}] as const;
export function progressFields():FieldSpec[]{return [{name:"date",label:"Data da avaliação",type:"date",value:today(),required:true},...indicators.map(i=>({name:i.key,label:i.label,options:["1","2","3","4","5"],value:"3"})),{name:"mainImprovement",label:"Maior evolução",type:"textarea"},{name:"attentionPoint",label:"Ponto que ainda precisa de atenção",type:"textarea"}];}
export function goalFields():FieldSpec[]{return [{name:"title",label:"Objetivo",required:true},{name:"description",label:"Descrição",type:"textarea"},{name:"targetDate",label:"Prazo (opcional)",type:"date"},{name:"progress",label:"Progresso manual (1 a 5)",options:["1","2","3","4","5"],value:"1"},{name:"status",label:"Status",options:[{value:"ongoing",label:"Em andamento"},{value:"achieved",label:"Alcançado"},{value:"paused",label:"Pausado"}],value:"ongoing"}];}
export function paymentFields():FieldSpec[]{return [{name:"description",label:"Descrição",required:true},{name:"amount",label:"Valor (R$)",type:"number",required:true,min:0.01,step:"0.01"},{name:"dueDate",label:"Vencimento",type:"date",required:true,value:today()},{name:"paidAt",label:"Data do pagamento",type:"date"},{name:"paymentMethod",label:"Forma de pagamento",placeholder:"Pix, dinheiro, transferência…"},{name:"status",label:"Status",options:[{value:"pending",label:"Pendente"},{value:"paid",label:"Pago"},{value:"overdue",label:"Atrasado"}],value:"pending"}];}
