import {and,asc,desc,eq,gte,lte} from "drizzle-orm";
import {database} from "@/db";
import {lessons,progressEntries,studentGoals,teacherProfiles,reports,activityLogs} from "@/db/schema";
import {ownedStudent} from "./tenancy";
import {periodSchema,reportSchema,uuidSchema} from "./validation";
import {AppError} from "./errors";
import {indicators} from "./fields";
import type {z} from "zod";
const join=(values:string[])=>[...new Set(values.map(v=>v.trim()).filter(Boolean))].join("\n");
export type ReportSnapshot={studentName:string;teacherName:string;subject:string;professionalName:string;logoUrl:string|null;attendance:string;progress:string;goals:string;phone:string;email:string|null};
export async function buildReportDraft(owner:string,input:z.input<typeof periodSchema>){const period=periodSchema.parse(input);if((Date.parse(period.periodEnd)-Date.parse(period.periodStart))/86400000>366)throw new AppError("Escolha um período de até um ano.");const student=await ownedStudent(owner,period.studentId);const db=database();const rows=await db.select().from(lessons).where(and(eq(lessons.accessCodeId,owner),eq(lessons.studentId,student.id),gte(lessons.date,period.periodStart),lte(lessons.date,period.periodEnd))).orderBy(asc(lessons.date));const completed=rows.filter(l=>["completed","makeup"].includes(l.status));const evaluations=await db.select().from(progressEntries).where(and(eq(progressEntries.accessCodeId,owner),eq(progressEntries.studentId,student.id),gte(progressEntries.date,period.periodStart),lte(progressEntries.date,period.periodEnd))).orderBy(asc(progressEntries.date),asc(progressEntries.createdAt));const [baseline]=await db.select().from(progressEntries).where(and(eq(progressEntries.accessCodeId,owner),eq(progressEntries.studentId,student.id),lte(progressEntries.date,period.periodStart))).orderBy(desc(progressEntries.date),desc(progressEntries.createdAt)).limit(1);const goals=await db.select().from(studentGoals).where(and(eq(studentGoals.accessCodeId,owner),eq(studentGoals.studentId,student.id))).limit(100);const [teacher]=await db.select().from(teacherProfiles).where(eq(teacherProfiles.accessCodeId,owner));if(!teacher)throw new AppError("Configure seu perfil antes de gerar um relatório.");const last=evaluations.at(-1);const first=baseline??evaluations[0];const absence=rows.filter(l=>l.status==="absent").length;const snapshot:ReportSnapshot={studentName:student.name,teacherName:teacher.name,professionalName:teacher.professionalName,subject:student.subject,logoUrl:teacher.logoUrl,attendance:`${completed.length} aulas realizadas; ${absence} faltas (${rows.filter(l=>l.status==="absent"&&l.justifiedAbsence).length} justificadas).`,progress:last&&first?indicators.map(i=>`${i.label}: ${first[i.key]} → ${last[i.key]} (escala 1 a 5)`).join("\n"):"Sem avaliação de evolução no período.",goals:goals.map(g=>`${g.title}: ${g.progress}/5 · ${g.status==="achieved"?"alcançado":g.status==="paused"?"pausado":"em andamento"}`).join("\n"),phone:teacher.phone,email:teacher.email};return {...period,lessonsCount:completed.length,contents:join(completed.map(l=>l.content)),improvements:join([...completed.map(l=>l.achievement),...evaluations.map(e=>e.mainImprovement)]),attentionPoints:join([...completed.map(l=>l.difficulty),...evaluations.map(e=>e.attentionPoint)]),participationRating:"Boa" as const,activitiesRating:"Boa" as const,generalProgress:"Evolução gradual" as const,nextGoals:join([...goals.filter(g=>g.status==="ongoing").map(g=>g.title),...completed.slice(-1).map(l=>l.nextFocus)]),teacherMessage:"",snapshot,student,teacher};}
export async function ownedReport(owner:string,id:string){uuidSchema.parse(id);const [row]=await database().select().from(reports).where(and(eq(reports.id,id),eq(reports.accessCodeId,owner)));if(!row)throw new AppError("Relatório não encontrado.");return row;}
export async function saveReport(owner:string,input:z.input<typeof reportSchema>,id?:string){const data=reportSchema.parse(input);if(id)await ownedReport(owner,id);const draft=await buildReportDraft(owner,data);return database().transaction(async tx=>{const values={...data,accessCodeId:owner,lessonsCount:draft.lessonsCount,snapshot:JSON.stringify(draft.snapshot),generatedAt:new Date()};const [row]=id?await tx.update(reports).set(values).where(and(eq(reports.id,id),eq(reports.accessCodeId,owner))).returning():await tx.insert(reports).values(values).returning();if(!row)throw new AppError("Relatório não encontrado.");await tx.insert(activityLogs).values({accessCodeId:owner,message:`Relatório de ${draft.student.name} foi gerado.`});return row;});}
