import {notFound} from "next/navigation";
import {and,desc,eq} from "drizzle-orm";
import {database} from "@/db";
import {lessonPackages} from "@/db/schema";
import {requireTeacher} from "@/lib/auth";
import {ownedStudent} from "@/lib/tenancy";
import {PageHead} from "@/components/ui";
import {StudentTabs} from "@/components/student-tabs";
import {ActionForm,Fields,Field} from "@/components/action-form";
import {packageFields} from "@/lib/fields";
import {packageAction} from "../../../aulas/lesson-actions";
import {formatDate,money} from "@/lib/format";
export default async function StudentPackage({params}:{params:Promise<{id:string}>}){const access=await requireTeacher();const {id}=await params;const s=await ownedStudent(access.id,id).catch(()=>notFound());const rows=await database().select().from(lessonPackages).where(and(eq(lessonPackages.accessCodeId,access.id),eq(lessonPackages.studentId,id))).orderBy(desc(lessonPackages.createdAt)).limit(30);const current=rows.find(p=>p.status==="current");return <><PageHead title={s.name} description="Pacotes de aulas"/><StudentTabs id={id} active="Pacote"/><div className="grid items-start gap-6 lg:grid-cols-2"><div className="space-y-5">{current?<section className="panel"><h2>Pacote atual</h2><div className="my-5 flex justify-between"><strong className="text-2xl">{current.totalLessons} aulas</strong><span>{money(current.value)}</span></div><label className="text-sm" htmlFor="package-progress">{current.usedLessons} / {current.totalLessons} aulas usadas</label><progress id="package-progress" value={current.usedLessons} max={current.totalLessons} className="mt-3 h-2 w-full accent-blue"/><p className="my-4">{current.totalLessons-current.usedLessons} aulas restantes</p>{current.totalLessons-current.usedLessons<=2&&<span className="badge warning">Próximo da renovação</span>}<p className="muted mt-5 text-sm">Início: {formatDate(current.startDate)} · Renovação: {formatDate(current.renewalDate)}</p></section>:<p className="panel muted">Nenhum pacote contratado. Aulas avulsas podem ser registradas normalmente.</p>}<section className="panel"><h2 className="mb-4">Pacotes anteriores</h2>{rows.filter(p=>p.status==="closed").map(p=><div className="border-t border-slate-100 py-3 text-sm" key={p.id}>{formatDate(p.startDate)} · {p.usedLessons}/{p.totalLessons} aulas · {money(p.value)}</div>)}</section></div><section className="panel"><h2 className="mb-5">{current?"Renovar pacote":"Adicionar pacote"}</h2><p className="muted mb-5 text-sm">O pacote anterior será preservado no histórico. Faltas e cancelamentos não consomem aulas.</p><ActionForm action={packageAction} submit={current?"Renovar pacote":"Salvar pacote"} confirm={current?"Encerrar o pacote atual e criar um novo? O saldo anterior ficará no histórico.":undefined}><Field type="hidden" name="studentId" label="Aluno" value={id}/><Fields fields={packageFields()}/></ActionForm></section></div></>;}
