import {test,after} from "node:test";
import assert from "node:assert/strict";
import {eq,and} from "drizzle-orm";
import {database,closeDatabase} from "../../src/db";
import {accessCodes,makeupRequests,makeupSlots,responsibleContacts,responsibleStudentAccess,responsibleSessions} from "../../src/db/schema";
import {createAccess} from "../../src/lib/admin-service";
import {saveStudent} from "../../src/lib/student-service";
import {createResponsibleAccess,changeResponsibleStatus,regenerateResponsibleCode,deleteResponsibleAccess,listResponsibleAccess,savePortalSettings,getPortalSettings,createMakeupSlot,changeMakeupSlotStatus,requestMakeupSlot,decideMakeupRequest,cancelMakeupRequest} from "../../src/lib/responsible-service";
process.env.DATABASE_URL=process.env.TEST_DATABASE_URL;process.env.SESSION_SECRET="integration-only-not-a-production-secret";
if(!process.env.DATABASE_URL?.includes("evolucao_test"))throw new Error("Banco isolado obrigatório.");
const ids:string[]=[];after(async()=>{for(const id of ids)await database().delete(accessCodes).where(eq(accessCodes.id,id));await closeDatabase();});
function student(){return {name:"Maria",birthDate:null,age:null,grade:"7",school:"",subject:"Matemática",startDate:"2026-10-01",frequency:"",responsibleName:"",responsiblePhone:"",responsibleEmail:null,mainGoal:"",difficulties:"",strengths:"",notes:""};}
test("portal: criar acesso, listar, bloquear, regenerar e excluir com tenancy",async()=>{
  const a=await createAccess({customerName:"A",customerEmail:null,plan:"individual",studentLimit:10,code:null});
  const b=await createAccess({customerName:"B",customerEmail:null,plan:"individual",studentLimit:10,code:null});
  ids.push(a.id,b.id);
  const s=await saveStudent(a.id,student());
  await assert.rejects(()=>createResponsibleAccess(b.id,s.id,{name:"Mãe",phone:"",email:null,code:null}),/não encontrado/);
  const access=await createResponsibleAccess(a.id,s.id,{name:"Mãe da Maria",phone:"11999999999",email:null,code:null});
  assert.match(access.code,/^[A-Z]{3}-\d[A-Z]\d{2}$/);
  assert.equal((await listResponsibleAccess(b.id,s.id)).length,0);
  assert.equal((await listResponsibleAccess(a.id,s.id)).length,1);
  const manual=await createResponsibleAccess(a.id,s.id,{name:"Pai da Maria",phone:"",email:null,code:"PAPA2026"});
  assert.equal(manual.code,"PAPA2026");
  await assert.rejects(()=>createResponsibleAccess(a.id,s.id,{name:"Pai da Maria",phone:"",email:null,code:"PAPA2026"}),/já existe/);
  await changeResponsibleStatus(a.id,access.id,"blocked");
  const [row]=await database().select().from(responsibleStudentAccess).where(eq(responsibleStudentAccess.id,access.id));
  assert.equal(row.status,"blocked");
  await assert.rejects(()=>changeResponsibleStatus(b.id,access.id,"active"),/não encontrado/);
  const code2=await regenerateResponsibleCode(a.id,access.id);
  assert.notEqual(code2,access.code);
  await deleteResponsibleAccess(a.id,access.id);
  assert.equal((await listResponsibleAccess(a.id,s.id)).length,1);
  await deleteResponsibleAccess(a.id,manual.id);
  const [contact]=await database().select().from(responsibleContacts).where(and(eq(responsibleContacts.accessCodeId,a.id),eq(responsibleContacts.name,"Pai da Maria")));
  assert.equal(contact,undefined);
});
test("portal: preferências padrão, salvar e consultar",async()=>{
  const a=await createAccess({customerName:"A",customerEmail:null,plan:"individual",studentLimit:10,code:null});
  ids.push(a.id);
  const d=await getPortalSettings(a.id);
  assert.equal(d.enabled,true);assert.equal(d.showReports,true);
  await savePortalSettings(a.id,{enabled:true,showFinance:false,showProgress:true,showLessonContent:true,showReports:true,rulesPayment:"À vista",rulesCancellation:"",rulesReplacement:"",schedules:"",materials:"",otherInfo:""});
  const s=await getPortalSettings(a.id);
  assert.equal(s.showFinance,false);
  assert.equal(s.rulesPayment,"À vista");
});
test("reposição: abrir horário, solicitar, decidir e cancelar com tenancy",async()=>{
  const a=await createAccess({customerName:"A",customerEmail:null,plan:"individual",studentLimit:10,code:null});
  const b=await createAccess({customerName:"B",customerEmail:null,plan:"individual",studentLimit:10,code:null});
  ids.push(a.id,b.id);
  const s=await saveStudent(a.id,student());
  const access=await createResponsibleAccess(a.id,s.id,{name:"Mãe",phone:"",email:null,code:null});
  const slot=await createMakeupSlot(a.id,{date:"2030-01-10",startTime:"15:00",endTime:"16:00"});
  await assert.rejects(()=>requestMakeupSlot(b.id,access.id,s.id,slot.id),/não encontrado/);
  await requestMakeupSlot(a.id,access.id,s.id,slot.id);
  let [req]=await database().select().from(makeupRequests).where(eq(makeupRequests.slotId,slot.id));
  let [sl]=await database().select().from(makeupSlots).where(eq(makeupSlots.id,slot.id));
  assert.equal(req.status,"pending");
  assert.equal(sl.status,"requested");
  await assert.rejects(()=>requestMakeupSlot(a.id,access.id,s.id,slot.id),/disponível|pendente/);
  await decideMakeupRequest(a.id,req.id,"approved");
  [sl]=await database().select().from(makeupSlots).where(eq(makeupSlots.id,slot.id));
  [req]=await database().select().from(makeupRequests).where(eq(makeupRequests.id,req.id));
  assert.equal(sl.status,"confirmed");
  assert.equal(req.status,"approved");
  const closed=await createMakeupSlot(a.id,{date:"2030-01-20",startTime:"10:00",endTime:"11:00"});
  await changeMakeupSlotStatus(a.id,closed.id,"unavailable");
  await assert.rejects(()=>requestMakeupSlot(a.id,access.id,s.id,closed.id),/não está mais disponível/);
  const slot3=await createMakeupSlot(a.id,{date:"2030-02-01",startTime:"14:00",endTime:"15:00"});
  await requestMakeupSlot(a.id,access.id,s.id,slot3.id);
  const [req3]=await database().select().from(makeupRequests).where(eq(makeupRequests.slotId,slot3.id));
  await decideMakeupRequest(a.id,req3.id,"rejected");
  [sl]=await database().select().from(makeupSlots).where(eq(makeupSlots.id,slot3.id));
  assert.equal(sl.status,"available");
  const other=await createResponsibleAccess(a.id,s.id,{name:"Avó",phone:"",email:null,code:null});
  await assert.rejects(()=>cancelMakeupRequest(a.id,other.id,req3.id),/não encontrada/);
  await requestMakeupSlot(a.id,access.id,s.id,slot3.id);
  const [req4]=await database().select().from(makeupRequests).where(and(eq(makeupRequests.slotId,slot3.id),eq(makeupRequests.status,"pending")));
  await cancelMakeupRequest(a.id,access.id,req4.id);
  [req]=await database().select().from(makeupRequests).where(eq(makeupRequests.id,req4.id));
  [sl]=await database().select().from(makeupSlots).where(eq(makeupSlots.id,slot3.id));
  assert.equal(req.status,"cancelled");
  assert.equal(sl.status,"available");
  const [sessions]=await database().select().from(responsibleSessions);
  assert.equal(sessions,undefined);
});