"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {Home,Users,Plus,FileText,MoreHorizontal,BookOpen,Wallet,Package,MessageSquare,Settings,User,LogOut,Handshake} from "lucide-react";
import {Brand} from "./ui";
import {teacherLogoutAction} from "@/app/actions";
const primary=[{href:"/dashboard",label:"Início",icon:Home},{href:"/alunos",label:"Alunos",icon:Users},{href:"/aulas",label:"Aulas",icon:BookOpen},{href:"/relatorios",label:"Relatórios",icon:FileText}];
const secondary=[{href:"/pacotes",label:"Pacotes",icon:Package},{href:"/financeiro",label:"Financeiro",icon:Wallet},{href:"/mensagens",label:"Mensagens",icon:MessageSquare},{href:"/portal",label:"Portal do Responsável",icon:Handshake},{href:"/perfil",label:"Perfil",icon:User},{href:"/configuracoes",label:"Configurações",icon:Settings}];
export function Navigation({name}:{name:string}){const path=usePathname();return <><aside className="fixed inset-y-0 left-0 z-30 hidden w-62 flex-col bg-navy px-5 pb-6 pt-8 md:flex"><Brand light/><p className="mb-8 mt-8 px-3 text-xs text-slate-300">SEU ACOMPANHAMENTO</p><nav aria-label="Principal" className="space-y-1">{primary.map(i=><Link key={i.href} className={`nav-link ${path.startsWith(i.href)?"active":""}`} href={i.href}><i.icon size={19}/>{i.label}</Link>)}</nav><div className="my-5 border-t border-white/10"/><nav aria-label="Mais" className="space-y-1">{secondary.map(i=><Link key={i.href} className={`nav-link ${path.startsWith(i.href)?"active":""}`} href={i.href}><i.icon size={18}/>{i.label}</Link>)}</nav><div className="mt-auto pt-8"><p className="truncate px-4 text-sm font-medium text-white">{name}</p><p className="mb-3 mt-1 px-4 text-xs text-slate-300">Evolução Visível Individual</p><form action={teacherLogoutAction}><button className="nav-link w-full"><LogOut size={18}/>Sair</button></form></div></aside><nav aria-label="Navegação mobile" className="fixed inset-x-0 bottom-0 z-30 grid grid-cols-5 border-t border-slate-200 bg-white px-2 pb-[max(env(safe-area-inset-bottom),8px)] pt-2 md:hidden">{[primary[0],primary[1],{href:"/aulas/nova",label:"+ Aula",icon:Plus},primary[3],{href:"/mais",label:"Mais",icon:MoreHorizontal}].map((i,n)=><Link key={i.href} className={`flex min-h-13 flex-col items-center justify-center gap-1 rounded-xl text-[11px] font-semibold ${n===2?"bg-navy text-white":path.startsWith(i.href)?"bg-slate-100 text-navy":"text-slate-600"}`} href={i.href}><i.icon size={21}/>{i.label}</Link>)}</nav></>;}
