import Link from "next/link";
import {notFound} from "next/navigation";
import {requireTeacher} from "@/lib/auth";
import {ownedReport,type ReportSnapshot} from "@/lib/report-service";
import {ownedStudent} from "@/lib/tenancy";
import {PageHead,Value} from "@/components/ui";
import {EditableMessage} from "@/components/copy";
import {reportMessage} from "@/lib/messages";
import {formatDate} from "@/lib/format";
export default async function ReportDetail({params}:{params:Promise<{id:string}>}){const access=await requireTeacher();const {id}=await params;const r=await ownedReport(access.id,id).catch(()=>notFound());const s=await ownedStudent(access.id,r.studentId);const snapshot:ReportSnapshot=JSON.parse(r.snapshot);const msg=reportMessage({responsible:s.responsibleName,student:snapshot.studentName,start:r.periodStart,end:r.periodEnd,improvement:r.improvements,goal:r.nextGoals});return <><PageHead title={`Acompanhamento de ${snapshot.studentName}`} description={`${formatDate(r.periodStart)} a ${formatDate(r.periodEnd)}`}><div className="flex gap-3"><Link href={`/relatorios/${id}/editar`} className="button secondary">Editar prévia</Link><a className="button" href={`/api/relatorios/${id}/pdf`}>Baixar PDF</a></div></PageHead><div className="grid items-start gap-6 lg:grid-cols-[1.5fr_1fr]"><article className="panel"><div className="mb-7 border-b border-slate-200 pb-6"><h2>Relatório de Acompanhamento</h2><p className="muted mt-2">{snapshot.teacherName} · {snapshot.subject} · {r.lessonsCount} aulas</p></div><Value label="Conteúdos trabalhados">{r.contents}</Value><Value label="Principais avanços">{r.improvements}</Value><Value label="Pontos de atenção">{r.attentionPoints}</Value><Value label="Presença">{snapshot.attendance}</Value><Value label="Participação">{r.participationRating}</Value><Value label="Realização das atividades">{r.activitiesRating}</Value><Value label="Evolução geral">{r.generalProgress}</Value><Value label="Evolução avaliada">{snapshot.progress}</Value><Value label="Próximos objetivos">{r.nextGoals}</Value><Value label="Mensagem do professor">{r.teacherMessage}</Value></article><section className="panel"><h2 className="mb-5">Enviar ao responsável</h2><p className="muted mb-5 text-sm">Revise a mensagem, copie e envie junto com o PDF.</p><EditableMessage text={msg}/></section></div></>;}
