import {listResponsibleAccess,responsibleAccessMessage} from "@/lib/responsible-service";
import {ActionForm,Field} from "@/components/action-form";
import {CopyButton} from "@/components/copy";
import {ResponsibleCodeField} from "@/components/responsible-code";
import {responsibleCreateAction,responsibleDeleteAction,responsibleRegenerateAction,responsibleStatusAction} from "../responsible-actions";

export async function ResponsibleAccessCard({owner,studentId,studentName,defaults,highlight}:{owner:string;studentId:string;studentName:string;defaults:{name:string;phone:string;email:string|null};highlight?:{id:string;status?:string}}){
  const rows=await listResponsibleAccess(owner,studentId);
  const shown=highlight?rows.find(r=>r.access.id===highlight.id):undefined;
  return <section className="panel mt-6"><h2>Acesso do responsável</h2>
    <p className="muted mt-2 text-sm">Um código individual permite que o responsável acompanhe aulas, evolução, financeiro e reposições pelo celular, somente leitura.</p>
    {shown&&<div className="mt-5 rounded-xl border border-green-200 bg-green-50 p-4"><p className="font-semibold text-green-800">{highlight?.status==="regenerado"?"Novo código gerado com sucesso. O código anterior parou de funcionar.":"Acesso criado com sucesso"}</p><p className="mt-2 text-2xl font-bold tracking-widest text-navy">{shown.access.code}</p><div className="mt-3 flex flex-wrap gap-2"><CopyButton text={shown.access.code} label="Copiar código"/><CopyButton text={responsibleAccessMessage(shown.contact.name,studentName,shown.access.code)} label="Copiar mensagem"/></div></div>}
    {rows.length>0?<ul className="mt-5 space-y-3">{rows.map(({access,contact})=><li key={access.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">{contact.name}</p><p className="muted mt-1 text-sm">{contact.phone||"Sem telefone"}{contact.email?` · ${contact.email}`:""}</p></div><div className="flex items-center gap-2"><span className={`badge ${access.status==="active"?"success":"warning"}`}>{access.status==="active"?"Ativo":"Bloqueado"}</span><span className="font-mono text-sm font-semibold">{access.code}</span></div></div><p className="muted mt-2 text-xs">Último acesso: {access.lastAccessAt?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(access.lastAccessAt):"nunca"}</p>
      <div className="mt-3 flex flex-wrap gap-2"><ActionForm action={responsibleStatusAction} submit={access.status==="active"?"Bloquear":"Reativar"} confirm={access.status==="active"?"Bloquear este acesso? O responsável será desconectado.":"Reativar este acesso?"}><Field name="studentId" label="Aluno" type="hidden" value={studentId}/><Field name="id" label="Acesso" type="hidden" value={access.id}/><Field name="status" label="Situação" type="hidden" value={access.status==="active"?"blocked":"active"}/></ActionForm>
        <ActionForm action={responsibleRegenerateAction} submit="Regenerar código" confirm="Regenerar o código? O código atual parará de funcionar imediatamente."><Field name="studentId" label="Aluno" type="hidden" value={studentId}/><Field name="id" label="Acesso" type="hidden" value={access.id}/></ActionForm>
        <ActionForm action={responsibleDeleteAction} submit="Excluir acesso" confirm="Excluir este acesso do responsável? O código deixará de funcionar."><Field name="studentId" label="Aluno" type="hidden" value={studentId}/><Field name="id" label="Acesso" type="hidden" value={access.id}/></ActionForm></div></li>)}</ul>:<p className="muted mt-4 text-sm">Nenhum acesso de responsável cadastrado para este aluno.</p>}
    <details className="mt-5"><summary className="button secondary inline-flex cursor-pointer">Criar acesso</summary><div className="mt-5 border-t border-slate-100 pt-5"><ActionForm action={responsibleCreateAction} submit="Criar acesso"><Field name="studentId" label="Aluno" type="hidden" value={studentId}/><div className="grid gap-5 md:grid-cols-2"><Field name="name" label="Nome do responsável" required value={defaults.name} placeholder="Ex.: Ana Paula"/><Field name="phone" label="Telefone" type="tel" value={defaults.phone} placeholder="(84) 98604-9708"/><Field name="email" label="E-mail (opcional)" type="email" value={defaults.email??""}/></div><div className="mt-5"><ResponsibleCodeField/></div></ActionForm></div></details>
  </section>;
}
